services:
  agent:
    env_file: [.env]
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run'
    build:
      context: ./
      dockerfile: dockerfile_agent
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
  mongo:
    command: mongod
    image: mongo:4.0.0

  db:
    container_name: db_main
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_NAME=admin
    image: postgres:16rc1-alpine3.18

  proxy-server:
    build: DataExchangeService
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=db
    depends_on:
      - db
version: '3.7'
