services:
  agent:
    env_file: [.env]
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run'
    build:
      context: ./
      dockerfile: dockerfile_agent
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  db:
    container_name: db_main
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:16rc1-alpine3.18

  proxy-server:
    build: DataExchangeService
    ports:
      - "5433:5433"
    depends_on:
      - db
    environment:
      - PATH=/
